export const FETCH_ROOMS_REQUEST = "FETCH_ROOMS_REQUEST"
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS"
export const FETCH_ROOMS_FAILURE = "FETCH_ROOMS_FAILURE"

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const BOOKED_ROOM = "BOOKED_ROOM";

export const SET_LENGTH_ROOM = 'SET_LENGTH_ROOM';
export const SET_BOOKED_LENGTH_ROOM = 'SET_BOOKED_LENGTH_ROOM';
export const SET_BOOKED_ROOM = 'SET_BOOKED_ROOM';



